USE Todo;
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255),
  `password` VARCHAR(255),
  firstName VARCHAR(255), 
  lastName VARCHAR(255),
  created_at TIMESTAMP default CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTO_INCREMENT, 
  task VARCHAR(255), 
  `status` VARCHAR(255),
  user_id INTEGER,
  created_at TIMESTAMP default CURRENT_TIMESTAMP,
  updated_at TIMESTAMP default CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY(user_id) REFERENCES users (id)
);